[package]
name = "libcnb-rs"
version = "0.1.0"
authors = ["Terence Lee <hone02@gmail.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.5"
